// SUP-board cup holder with integrated phone pocket
// All dimensions in millimetres. STL is generated by generate_sup_holder.py.
$fn = 128;

cup_inner_d = 76;
cup_wall = 3;
cup_outer_d = 82;
cup_inner_h = 100;
cup_floor = 3;
slot_width = 7;

platform_d = 110;
platform_h = 5;

phone_inner_w = 81;
phone_inner_d = 16;
phone_inner_h = 80;
phone_wall = 3;
phone_floor = 5;
phone_outer_w = phone_inner_w + 2 * phone_wall;
phone_outer_d = phone_inner_d + 2 * phone_wall;

cup_floor_z = platform_h + cup_floor;
cup_top_z = cup_floor_z + cup_inner_h;
phone_x0 = cup_outer_d / 2 - 3;
phone_center_x = phone_x0 + phone_outer_w / 2;
phone_top_z = platform_h + phone_floor + phone_inner_h;

module rounded_box(size, r) {
    linear_extrude(size[2])
        offset(r=r) square([size[0] - 2*r, size[1] - 2*r], center=true);
}

module platform() {
    union() {
        cylinder(d=platform_d, h=platform_h);
        translate([phone_center_x, 0, 0])
            rounded_box([phone_outer_w, phone_outer_d + 8, platform_h], 5);
    }
}

module slotted_cup() {
    difference() {
        difference() {
            translate([0, 0, platform_h]) cylinder(d=cup_outer_d, h=cup_top_z-platform_h);
            translate([0, 0, cup_floor_z]) cylinder(d=cup_inner_d, h=cup_inner_h+1);
        }
        for (a=[45,135,225,315])
            rotate([0,0,a]) translate([(cup_outer_d+8)/2-1, 0, cup_floor_z+cup_inner_h/2])
                cube([cup_outer_d+8, slot_width, cup_inner_h+1], center=true);
    }
}

module phone_pocket() {
    difference() {
        translate([phone_center_x, 0, platform_h])
            rounded_box([phone_outer_w, phone_outer_d, phone_top_z-platform_h], 4);
        translate([phone_center_x, 0, platform_h+phone_floor])
            rounded_box([phone_inner_w, phone_inner_d, phone_inner_h+1], 2);
    }
}

module drain_holes() {
    for (a=[0,90,180,270]) {
        translate([15*cos(a),15*sin(a),-1]) cylinder(d=4,h=cup_floor_z+2);
        translate([15*cos(a),15*sin(a),cup_floor_z-1.2]) cylinder(d1=4,d2=6,h=1.3);
    }
    for (dx=[-22,22]) {
        translate([phone_center_x+dx,0,-1]) cylinder(d=4,h=platform_h+phone_floor+2);
        translate([phone_center_x+dx,0,platform_h+phone_floor-1.2]) cylinder(d1=4,d2=6,h=1.3);
    }
}

difference() {
    union() {
        platform();
        slotted_cup();
        phone_pocket();
        // Rounded reinforcement at both sides of the joint.
        for (y=[-phone_outer_d/2+2.5,phone_outer_d/2-2.5])
            translate([phone_x0+1,y,5]) cylinder(r=5,h=70);
    }
    drain_holes();
}
