// SUP-board cup holder with integrated phone pocket
// All dimensions in millimetres. STL is generated by generate_sup_holder.py.
$fn = 128;

cup_inner_d = 76;
cup_wall = 3;
cup_outer_d = 82;
cup_inner_h = 100;
cup_floor = 3;
slot_width = 7;
slot_corner_r = 3;

platform_d = 110;
platform_h = 5;

phone_inner_w = 81;
phone_inner_d = 16;
phone_inner_h = 80;
phone_wall = 3;
phone_floor = 5;
phone_outer_w = phone_inner_w + 2 * phone_wall;
phone_outer_d = phone_inner_d + 2 * phone_wall;

cup_floor_z = platform_h + cup_floor;
cup_top_z = cup_floor_z + cup_inner_h;
phone_x0 = cup_outer_d / 2 - 3;
phone_center_x = phone_x0 + phone_outer_w / 2;
phone_top_z = platform_h + phone_floor + phone_inner_h;

module rounded_box(size, r) {
    linear_extrude(size[2])
        offset(r=r) square([size[0] - 2*r, size[1] - 2*r], center=true);
}

module platform() {
    union() {
        cylinder(d=platform_d, h=platform_h);
        translate([phone_center_x, 0, 0])
            rounded_box([phone_outer_w, phone_outer_d + 8, platform_h], 5);
    }
}

module slotted_cup() {
    difference() {
        difference() {
            translate([0, 0, platform_h]) cylinder(d=cup_outer_d, h=cup_top_z-platform_h);
            translate([0, 0, cup_floor_z]) cylinder(d=cup_inner_d, h=cup_inner_h+1);
        }
        for (a=[45,135,225,315])
            rotate([0,0,a]) {
                slot_bottom_z = cup_floor_z + slot_width/2 - 2;
                slot_h = cup_top_z-slot_bottom_z+1;
                translate([(cup_outer_d+8)/2-1, 0, slot_bottom_z+slot_h/2])
                    cube([cup_outer_d+8, slot_width, slot_h], center=true);
                // Rounded lower end: the rope enters through the open top.
                translate([(cup_outer_d+8)/2-1,0,slot_bottom_z])
                    rotate([0,90,0]) cylinder(r=slot_width/2,h=cup_outer_d+8,center=true);
                // R3 safety rounding at both exposed upper corners.
                for (side=[-1,1])
                    translate([(cup_inner_d+cup_outer_d)/4,
                               side*(slot_width/2+slot_corner_r/2),
                               cup_top_z-slot_corner_r/2])
                        difference() {
                            cube([cup_wall+4,slot_corner_r,slot_corner_r],center=true);
                            translate([0,side*slot_corner_r/2,-slot_corner_r/2])
                                rotate([0,90,0]) cylinder(r=slot_corner_r,h=cup_wall+6,center=true);
                        }
            }
    }
}

module phone_pocket() {
    difference() {
        translate([phone_center_x, 0, platform_h])
            rounded_box([phone_outer_w, phone_outer_d, phone_top_z-platform_h], 4);
        translate([phone_center_x, 0, platform_h+phone_floor])
            rounded_box([phone_inner_w, phone_inner_d, phone_inner_h+1], 2);
    }
}

module engraving() {
    translate([phone_center_x,-phone_outer_d/2+0.1,50])
        rotate([90,0,0])
            linear_extrude(1.2)
                text("Red Rocket",size=10,font="Arial:style=Bold",halign="center",valign="center");
}

module drain_holes() {
    collector_turn=[12,101,207,296];
    for (i=[0:3]) {
        a=[0,90,180,270][i];
        translate([15*cos(a),15*sin(a),-1]) cylinder(d=4,h=cup_floor_z+2);
        translate([15*cos(a),15*sin(a),cup_floor_z-1.5])
            linear_extrude(1.5,scale=3)
                rotate(collector_turn[i])
                    offset(r=1.6) circle(r=2,$fn=3);
    }
    for (i=[0:1]) {
        dx=[-22,22][i];
        translate([phone_center_x+dx,0,-1]) cylinder(d=4,h=platform_h+phone_floor+2);
        translate([phone_center_x+dx,0,platform_h+phone_floor-1.5])
            linear_extrude(1.5,scale=3)
                rotate([-18,23][i])
                    offset(r=1.6) circle(r=2,$fn=3);
    }
}

module cup_clearance() {
    // Final clean Ø76 bore removes all reinforcement intrusions above the floor.
    translate([0,0,cup_floor_z]) cylinder(d=cup_inner_d,h=cup_inner_h+1);
}

module rope_runoff_channels() {
    // Applied to the completed assembly, so the channel pierces the outer wall,
    // reinforcement and platform instead of being filled by their later union.
    for (a=[45,135,225,315]) rotate([0,0,a]) {
        slot_bottom_z = cup_floor_z+slot_width/2-2;
        // Re-drill the complete vertical slot and U-bottom after assembly.
        translate([(cup_outer_d+8)/2-1,0,(slot_bottom_z+cup_top_z+1)/2])
            cube([cup_outer_d+8,slot_width,cup_top_z+1-slot_bottom_z],center=true);
        translate([(cup_outer_d+8)/2-1,0,slot_bottom_z])
            rotate([0,90,0]) cylinder(r=slot_width/2,h=cup_outer_d+8,center=true);
        // Constant 7 mm sidewalls; lower hulls retain the rounded U-floor.
        translate([48,0,(9.5+cup_top_z+2)/2])
            cube([24,slot_width,cup_top_z+2-9.5],center=true);
        hull() {
            translate([37,0,slot_bottom_z]) sphere(r=4);
            translate([41,0,slot_bottom_z]) sphere(r=4);
        }
        hull() {
            translate([41,0,slot_bottom_z]) sphere(r=4);
            translate([45.5,0,8]) sphere(r=4);
        }
        hull() {
            translate([45.5,0,8]) sphere(r=4);
            translate([50,0,6.5]) sphere(r=4);
        }
        hull() {
            translate([50,0,6.5]) sphere(r=4);
            translate([58,0,6.5]) sphere(r=4);
        }
    }
}

difference() {
    union() {
        platform();
        // External annular reinforcement; the hollow centre keeps drains open.
        difference() {
            translate([0,0,platform_h]) cylinder(r1=50,r2=41.5,h=8.5);
            translate([0,0,platform_h-1]) cylinder(r=40.5,h=10.5);
        }
        slotted_cup();
        phone_pocket();
        // Rounded reinforcement at both sides of the joint.
        for (y=[-phone_outer_d/2+2.5,phone_outer_d/2-2.5])
            translate([phone_x0+1,y,5]) cylinder(r=5,h=70);
    }
    drain_holes();
    cup_clearance();
    rope_runoff_channels();
    engraving();
}
